name: Publish Release on Itch.io

on:
  push:
    branches: ["release"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          # Use the GitHub Actions workflow cache to cache the Godot export templates and Godot executable. 
          # Helps speed up builds by not having to download them every time.
          cache: true
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Publish to Itch
        uses: Ayowel/butler-to-itch@v1.2.0
        with:
          butler_key: ${{secrets.ITCHIO_RELEASE}}
          itch_user: unprecedented
          itch_game: 2025-gamedevtv-game-jam
          version: ${{ github.ref_name }}
          files: "${{ steps.export.outputs.archive_directory }}/Gamedev-2025-web.zip"
